apiVersion: v1
kind: Service
metadata:
  name: result
  namespace: default
spec:
  selector:
    app: result
  type: NodePort
  ports:
  - name: result
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30081