apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" (include "KubeVote.fullname" .) .Values.result.name | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "KubeVote.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "KubeVote.selectorLabels" (dict "component" .Values.result.name "Release" .Release "Chart" .Chart "Values" .Values) | nindent 4 }}

  type: {{ .Values.result.service.type }}
  ports:
  - name: {{ .Values.result.name }}
    protocol: TCP
    port: {{ .Values.result.service.port }}
    targetPort: {{ .Values.result.service.targetPort }}
    nodePort: {{ .Values.result.service.nodePort }}