apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    {{- include "KubeVote.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: master
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
