apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "KubeVote.fullname" . }}-vote
  labels:
    {{- include "KubeVote.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.vote.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "KubeVote.selectorLabels" (dict "component" "vote" "Release" .Release "Chart" .Chart "Values" .Values) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "KubeVote.podLabels" (dict "component" "vote" "Release" .Release "Chart" .Chart "Values" .Values) | nindent 8 }}

    spec:
      containers:
        - name: "{{ .Values.vote.name | default "vote" }}"
          image: "{{ .Values.vote.image.repository }}:{{ .Values.vote.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.vote.service.targetPort }}
              protocol: TCP
          {{- with .Values.probes.liveness }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.probes.readiness }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
  
          {{- with .Values.vote.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}