apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-%s" (include "KubeVote.fullname" .) .Values.worker.name | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "KubeVote.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.worker.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "KubeVote.selectorLabels" (dict "component" .Values.worker.name "Release" .Release "Chart" .Chart "Values" .Values) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "KubeVote.podLabels" (dict "component" .Values.worker.name "Release" .Release "Chart" .Chart "Values" .Values) | nindent 8 }}
    spec:
      containers:
        - name: "{{ .Values.worker.name | default "worker" }}"
          image: "{{ .Values.result.image.repository }}@{{ .Values.result.image.digest }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          {{- with .Values.worker.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}