apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-%s" (include "kube-vote.name" .) .Values.vote.name | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "kube-vote.labels" . | nindent 4 }}
spec:
  revisionHistoryLimit: {{ .Values.global.revisionHistoryLimit }}
  {{- if not .Values.vote.autoscaling.enabled }}
  replicas: {{ .Values.vote.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "kube-vote.selectorLabels" (dict "component" .Values.vote.name "Release" .Release "Chart" .Chart "Values" .Values) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kube-vote.podLabels" (dict "component" .Values.vote.name "Release" .Release "Chart" .Chart "Values" .Values) | nindent 8 }}
    spec:
      containers:
        - name: "{{ .Values.vote.name | default "vote" }}"
          image: "{{ .Values.vote.image.repository }}@{{ .Values.vote.image.digest }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.vote.service.targetPort }}
              protocol: TCP
          {{- with .Values.global.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.global.probes.liveness }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.global.probes.readiness }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: REDIS_HOST
              value: "{{ .Values.vote.redis_host }}"
          {{- with .Values.vote.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}