name: result image -> GHCR -> update Helm values

on:
  push:
    branches: ["master"]
    paths:
      - "src/result/**"
      - ".github/workflows/build-result.yaml"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  SERVICE: result
  IMAGE: ghcr.io/kastoni/kubevote-result              #ghcr.io/${{ github.repository_owner | toLower }}/KubeVote-result
  PATH_TO_HELM: ./helm/KubeVote

jobs:
  build_push_update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v6.0.1
        with:
          fetch-depth: 0
          ref: master

      - uses: docker/setup-qemu-action@v3.7.0
      - uses: docker/setup-buildx-action@v3.12.0

      - name: Login GHCR
        uses: docker/login-action@v3.6.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Meta tags
        id: meta
        uses: docker/metadata-action@v5.10.0
        with:
          images: ${{ env.IMAGE }}
          tags: |
            type=raw,value=latest
            type=sha,format=short
            type=sha,format=long
            type=semver,pattern={{version}},prefix=v
            type=semver,pattern={{major}}.{{minor}},prefix=v
            type=semver,pattern={{major}},prefix=v
          labels: |
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.version=${{ steps.meta.outputs.version }}
            org.opencontainers.image.created=${{ steps.meta.outputs.created }}


      - name: Build & Push
        id: build
        uses: docker/build-push-action@v6.18.0
        with:
          context: ./src/result
          file: ./src/result/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=result
          cache-to: type=gha,mode=max,scope=result
          sbom: true
          provenance: mode=max

      - name: Install yq (pinned)
        run: |
          YQ_VERSION="v4.50.1"
          curl -sSL -o /usr/local/bin/yq "https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_amd64"
          chmod +x /usr/local/bin/yq
          yq -V

      - name: Update Helm values with digest
        env:
          DIGEST: ${{ steps.build.outputs.digest }}
          IMAGE: ${{ env.IMAGE }}
          PATH_TO_HELM: ${{ env.PATH_TO_HELM }}
        run: |
          git checkout gitops
          cd ${{ env.PATH_TO_HELM}}
          # result.image.repository: ghcr.io/...-result
          # result.image.digest: sha256:...
          yq -i '.result.image.repository = strenv(IMAGE)' ./values.yaml
          yq -i '.result.image.digest = strenv(DIGEST)' ./values.yaml
          
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ./values.yaml
          git commit -m "chore(result): bump image to ${IMAGE}@${DIGEST}" || exit 0
          git push origin gitops
